// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaLb8CXwWCCRHu5okLuHjqC73zUf22qtk',
    appId: '1:364305144256:web:7d29a896eafcf9f2b61025',
    messagingSenderId: '364305144256',
    projectId: 'pocket-health-001',
    authDomain: 'pocket-health-001.firebaseapp.com',
    storageBucket: 'pocket-health-001.firebasestorage.app',
    measurementId: 'G-HTVR8H3QL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQy1iqcGoKdenZ-YP1EO0H77yT0r6H9pc',
    appId: '1:364305144256:android:e9e4fc3eb3520551b61025',
    messagingSenderId: '364305144256',
    projectId: 'pocket-health-001',
    storageBucket: 'pocket-health-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtozche8Cpqzd72Jg23ZUHqJ8Vut8Miw',
    appId: '1:364305144256:ios:cb56249f7eff0cb3b61025',
    messagingSenderId: '364305144256',
    projectId: 'pocket-health-001',
    storageBucket: 'pocket-health-001.firebasestorage.app',
    iosBundleId: 'com.example.pocketHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:ios:demo',
    messagingSenderId: '123456789',
    projectId: 'pocket-health-demo',
    storageBucket: 'pocket-health-demo.appspot.com',
    iosBundleId: 'com.example.pocketHealth',
  );
}